"""drop content_progress_status from learner_content_progress

Revision ID: 87f2a9433e0b
Revises: 9c32d430c563
Create Date: 2026-10-06 22:16:40.028346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f2a9433e0b'
down_revision: Union[str, Sequence[str], None] = '9c32d430c563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_content_progress', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_content_progress', sa.Column('status', postgresql.ENUM('not_opened', 'in_progress', 'completed', name='learner_content_progress_status'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
