"""drop progress_percent from learner_content_progress

Revision ID: 9c32d430c563
Revises: 5b7680c500b9
Create Date: 2026-10-06 21:19:04.545335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c32d430c563'
down_revision: Union[str, Sequence[str], None] = '5b7680c500b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'learner_content_progress', ['learner_id', 'content_id'])
    op.drop_column('learner_content_progress', 'progress_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_content_progress', sa.Column('progress_status', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'learner_content_progress', type_='unique')
    # ### end Alembic commands ###
